eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
server:
  port: 8761
spring:
  application:
    name: EUREKA-SERVER
  main:
    allowBeanDefinitionOverriding: true